on: push
jobs:
  conda:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Trigger Scoring
        shell: bash -l {0}
        run: |
          curl --request POST \
          --url 'https://api.github.com/repos/PGEHackathon/scoring/dispatches' \
          --header 'authorization: Bearer ${{secrets.PGEHACKATHON_SECRET_TOKEN}}' \
          --data '{"event_type": "trigger"}'
